DevSearch/api/urls.py
from django.urls import path
from .views import (getProject,
                    getProjects,
                    projectVote,
                    removeTag
                    )
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns=[
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('projects/',getProjects),
    path('project/<str:pk>/',getProject),
    path('project/<str:pk>/vote/', projectVote),
    path('remove/tag/',removeTag)
]

DevSearch/mysite/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .views import home
urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/reset/password/',auth_views.PasswordResetView.as_view(template_name='users/reset/reset_password.html'),
         name='reset_password'),

    path('accounts/reset/password/sent/',auth_views.PasswordResetDoneView.as_view(template_name='users/reset/reset_done.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/reset/reset.html'),
         name='password_reset_confirm'),

    path('accounts/reset/password/complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/reset/complete.html'),
         name='password_reset_complete'),

]+i18n_patterns(
    path('i18n/',include('django.conf.urls.i18n')),
    path('', home, name='profiles'),
    path('api/', include('api.urls')),
    path('projects/', include('projects.urls')),
    path('users/', include('users.urls')),
)

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
#     urlpatterns+=[
#         static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
#         static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
#     ]

handler404='mysite.views.handle_404'

DevSearch/users/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,models.CASCADE,null=True,blank=True)
    name=models.CharField(max_length=255,null=True,blank=True)
    email=models.EmailField(max_length=255,null=True,blank=True)
    username = models.CharField(max_length=255, null=True, blank=True)
    location = models.CharField(max_length=500, null=True, blank=True)
    short_intro=models.CharField(max_length=255,null=True,blank=True)
    bio=models.TextField(null=True,blank=True)
    #skills=models.ManyToManyField('Skill',)
    profile_image=models.ImageField(upload_to='profiles/',default='profiles/user-default.png',null=True,blank=True)
    social_github=models.CharField(max_length=255,null=True,blank=True)
    social_twitter = models.CharField(max_length=255, null=True, blank=True)
    social_linkedin = models.CharField(max_length=255, null=True, blank=True)
    social_youtube = models.CharField(max_length=255, null=True, blank=True)
    social_instagram = models.CharField(max_length=255, null=True, blank=True)
    social_whatsapp = models.CharField(max_length=255, null=True, blank=True)
    social_website = models.CharField(max_length=255, null=True, blank=True)
    social_telegram = models.CharField(max_length=255, null=True, blank=True)
    phone=models.CharField(max_length=255, null=True, blank=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user.username)

    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ''
        return url

class Skill(models.Model):
    owner=models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    name=models.CharField(max_length=255,null=True,blank=True)
    description=models.TextField(null=True,blank=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name)

class Message(models.Model):
    sender=models.ForeignKey(Profile,on_delete=models.SET_NULL,blank=True,null=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, blank=True, null=True,related_name='messages')
    name=models.CharField(max_length=255,blank=True,null=True)
    email = models.EmailField(max_length=255, blank=True, null=True)
    subject = models.CharField(max_length=255, blank=True, null=True)
    body=models.TextField()
    is_read=models.BooleanField(default=False,null=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering=['is_read','-created']


    @property
    def is_read_true(self):
        if self.is_read==False:
            self.is_read=True
            self.save()

DevSearch/templates/index.html
{% extends 'main.html' %}
{% load static %}
{% block title %} Home {% endblock title %}
{% block content %}
  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{% url 'profiles' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                placeholder="Search by developer name" value="{{search_query}}"/>
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          {% for profile in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.pk %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ profile.imageURL }}" alt="image" />
                  <div class="dev__meta">
                    {% if profile.name %}
                    <h3>{{ profile.name }}</h3>
                    {% endif %}
                    {% if profile.short_intro %}
                    <h5>{{ profile.short_intro }}</h5>
                    {% endif %}
                  </div>
                </div>
                <p class="dev__info">
                  {% if profile.bio %}
                  {{ profile.bio|truncatewords:50 }}
                  {% endif %}
                </p>
                <div class="dev__skills">
                  {% for skill in profile.skill_set.all %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill.name}}</small>
                  </span>
                  {% endfor %}
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

     {% include 'pagination.html' with queryset=profiles custom_range=custom_range %}

  </main>
{% endblock content %}

DevSearch/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />

  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'css/app.css' %}" />

  <title>{%block title%}{% endblock title%}</title>
</head>
<body>
<header>
    {% include 'navbar.html' %}
</header>
<main>{% block content %} {% endblock content %}</main>
<footer></footer>
</body>
<script src="{% static 'uikit/app.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</html>

DevSearch/templates/navbar.html
{% load static %}
{% load i18n %}
<!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="{% url 'profiles' %}" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'profiles' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'project' %}">Projects</a></li>

          {% if request.user.is_authenticated %}
          <li class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
           <li class="header__menuItem"><a href="{% url 'account' %}" class="btn btn--main--outline">My Account</a></li>
          <li class="header__menuItem"><a href="{% url 'logout' %}" class="btn btn--main--outline">Logout</a></li>
          {% else %}
           <li class="header__menuItem"><a href="{% url 'login' %}" class="btn btn--main--outline">Login</a></li>
           <li class="header__menuItem"><a href="{% url 'signup' %}" class="btn btn--main--outline">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

DevSearch/templates/pagination.html
{% if queryset.has_other_pages %}
<div class="pagination">
      <ul class="container">
        {% if queryset.has_previous %}
        <li><a href="?page={{queryset.previous_page_number}}" data-page="{{queryset.previous_page_number}}" class="btn page-link btn--disabled">&#10094; Prev</a></li>
        {% endif %}
        {% for page in custom_range %}
        {% if page is queryset.number %}
        <li><a href="?page={{page.number}}" data-page="{{page}}" class="btn page-link btn--sub">{{page}}</a></li>
        {% else %}
        <li><a href="?page={{page.number}}" data-page="{{page}}" class="btn page-link" >{{page}}</a></li>
        {% endif %}
        {% endfor %}
        {% if queryset.has_next %}
        <li><a href="?page={{queryset.next_page_number}}"  data-page="{{queryset.next_page_number}}" class="btn page-link">Next &#10095;</a></li>
        {% endif %}
      </ul>
    </div>
 {% endif %}